apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learn-argocd-15min
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/wahyu-sty/argocd-15min.git
    targetRevision: local
  destination:
    namespace: devel
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
