apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inalix-help
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: blue-green
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    helm:
      version: v3
      values: |
        ingress:
          enabled: true
          hosts:
            - blue.0a0b0109.nip.io

  destination:
    namespace: inalix-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
