apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/vfarcic/devops-toolkit.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        ingress:
          host: toolkit.0a0b0109.nip.io
      version: v3
  destination:
    namespace: 15min
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
