apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.1.1
    chart: nginx
    helm:
      parameters:
      - name: ingress.enabled
        value: 'true'
      - name: ingress.hostname
        value: nginx.0a0b0109.nip.io
  destination:
    namespace: inalix-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
